# coding: utf-8

"""
    TasksDJ API

    TasksDJ API  # noqa: E501

    OpenAPI spec version: v1
    Contact: meechanic.design@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tasksdjclient
from tasksdjclient.models.task_tag import TaskTag  # noqa: E501
from tasksdjclient.rest import ApiException


class TestTaskTag(unittest.TestCase):
    """TaskTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskTag(self):
        """Test TaskTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tasksdjclient.models.task_tag.TaskTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
