# coding: utf-8

"""
    TasksDJ API

    TasksDJ API  # noqa: E501

    OpenAPI spec version: v1
    Contact: meechanic.design@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tasksdjclient
from tasksdjclient.api.tasks_api import TasksApi  # noqa: E501
from tasksdjclient.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = tasksdjclient.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_create(self):
        """Test case for tasks_create

        """
        pass

    def test_tasks_delete(self):
        """Test case for tasks_delete

        """
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        """
        pass

    def test_tasks_partial_update(self):
        """Test case for tasks_partial_update

        """
        pass

    def test_tasks_read(self):
        """Test case for tasks_read

        """
        pass

    def test_tasks_update(self):
        """Test case for tasks_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
