# coding: utf-8

"""
    TasksDJ API

    TasksDJ API  # noqa: E501

    OpenAPI spec version: v1
    Contact: meechanic.design@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tasksdjclient
from tasksdjclient.api.api_token_auth_api import ApiTokenAuthApi  # noqa: E501
from tasksdjclient.rest import ApiException


class TestApiTokenAuthApi(unittest.TestCase):
    """ApiTokenAuthApi unit test stubs"""

    def setUp(self):
        self.api = tasksdjclient.api.api_token_auth_api.ApiTokenAuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_token_auth_create(self):
        """Test case for api_token_auth_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
