# coding: utf-8

"""
    TasksDJ API

    TasksDJ API  # noqa: E501

    OpenAPI spec version: v1
    Contact: meechanic.design@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tasksdjclient
from tasksdjclient.models.auth_token import AuthToken  # noqa: E501
from tasksdjclient.rest import ApiException


class TestAuthToken(unittest.TestCase):
    """AuthToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthToken(self):
        """Test AuthToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tasksdjclient.models.auth_token.AuthToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
